<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<html lang="fr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=figtree:400,500,600&display=swap" rel="stylesheet" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tw-elements/dist/css/tw-elements.min.css" />
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="{{ asset('js/script.js') }}"></script>

    <style>
        
        @font-face {
            font-family: brushScript;
            src: url('/font/BrushScriptOpti-Regular.otf');
        }

        .logo-ext {
            font-family: brushScript; 
            border-bottom: solid 4px #bbaf7b
        }

        .test {
            animation-name: rotate;
            animation-duration: 30s;
            animation-iteration-count: infinite;
            animation-timing-function: linear;
        }

        @keyframes rotate {
            from {
                transform: rotate(-360deg);
            }

            to {
                transform: rotate(360deg);
            }
        }

        /* ----------------------------------------------
        * Generated by Animista
        * w: http://animista.net, t: @cssanimista
        * ---------------------------------------------- */

        .slide-in-bottom {
            -webkit-animation: slide-in-bottom .5s cubic-bezier(.25, .46, .45, .94) both;
            animation: slide-in-bottom .5s cubic-bezier(.25, .46, .45, .94) both
        }

        .slide-in-bottom-h1 {
            -webkit-animation: slide-in-bottom .5s cubic-bezier(.25, .46, .45, .94) .5s both;
            animation: slide-in-bottom .5s cubic-bezier(.25, .46, .45, .94) .5s both
        }

        .slide-in-bottom-subtitle {
            -webkit-animation: slide-in-bottom .5s cubic-bezier(.25, .46, .45, .94) .75s both;
            animation: slide-in-bottom .5s cubic-bezier(.25, .46, .45, .94) .75s both
        }

        .fade-in {
            -webkit-animation: fade-in 1.2s cubic-bezier(.39, .575, .565, 1.000) 1s both;
            animation: fade-in 1.2s cubic-bezier(.39, .575, .565, 1.000) 1s both
        }

        .bounce-top-icons {
            -webkit-animation: bounce-top .9s 1s both;
            animation: bounce-top .9s 1s both
        }

        @-webkit-keyframes slide-in-bottom {
            0% {
                -webkit-transform: translateY(1000px);
                transform: translateY(1000px);
                opacity: 0
            }

            100% {
                -webkit-transform: translateY(0);
                transform: translateY(0);
                opacity: 1
            }
        }

        @keyframes slide-in-bottom {
            0% {
                -webkit-transform: translateY(1000px);
                transform: translateY(1000px);
                opacity: 0
            }

            100% {
                -webkit-transform: translateY(0);
                transform: translateY(0);
                opacity: 1
            }
        }

        @-webkit-keyframes bounce-top {
            0% {
                -webkit-transform: translateY(-45px);
                transform: translateY(-45px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in;
                opacity: 1
            }

            24% {
                opacity: 1
            }

            40% {
                -webkit-transform: translateY(-24px);
                transform: translateY(-24px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in
            }

            65% {
                -webkit-transform: translateY(-12px);
                transform: translateY(-12px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in
            }

            82% {
                -webkit-transform: translateY(-6px);
                transform: translateY(-6px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in
            }

            93% {
                -webkit-transform: translateY(-4px);
                transform: translateY(-4px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in
            }

            25%,
            55%,
            75%,
            87% {
                -webkit-transform: translateY(0);
                transform: translateY(0);
                -webkit-animation-timing-function: ease-out;
                animation-timing-function: ease-out
            }

            100% {
                -webkit-transform: translateY(0);
                transform: translateY(0);
                -webkit-animation-timing-function: ease-out;
                animation-timing-function: ease-out;
                opacity: 1
            }
        }

        @keyframes bounce-top {
            0% {
                -webkit-transform: translateY(-45px);
                transform: translateY(-45px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in;
                opacity: 1
            }

            24% {
                opacity: 1
            }

            40% {
                -webkit-transform: translateY(-24px);
                transform: translateY(-24px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in
            }

            65% {
                -webkit-transform: translateY(-12px);
                transform: translateY(-12px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in
            }

            82% {
                -webkit-transform: translateY(-6px);
                transform: translateY(-6px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in
            }

            93% {
                -webkit-transform: translateY(-4px);
                transform: translateY(-4px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in
            }

            25%,
            55%,
            75%,
            87% {
                -webkit-transform: translateY(0);
                transform: translateY(0);
                -webkit-animation-timing-function: ease-out;
                animation-timing-function: ease-out
            }

            100% {
                -webkit-transform: translateY(0);
                transform: translateY(0);
                -webkit-animation-timing-function: ease-out;
                animation-timing-function: ease-out;
                opacity: 1
            }
        }

        @-webkit-keyframes fade-in {
            0% {
                opacity: 0
            }

            100% {
                opacity: 1
            }
        }

        @keyframes fade-in {
            0% {
                opacity: 0
            }

            100% {
                opacity: 1
            }
        }
    </style>

</head>


<body class="font-sans text-gray-900 antialiased">

    <!-- Navigation bar -->
    <nav style="background-color: #4f4949"
        class="fixed z-50 flex w-full items-center justify-between py-2 text-neutral-600 hover:text-neutral-700 focus:text-neutral-700 dark:bg-neutral-600 dark:text-neutral-200 md:flex-wrap md:justify-start"
        data-te-navbar-ref>
        <div class="flex w-full flex-wrap items-center justify-between px-1 md:px-3">

            <!-- Navigation links -->
            <div class="grow basis-[100%] items-center !flex lg:basis-auto">

                <div class="w-full container mx-auto px-2 md:px-6 py-2">

                    <div class="w-full flex items-center justify-between">
                        <div>
                            <a class="flex items-center no-underline hover:no-underline font-bold text-2xl lg:text-4xl"
                                href="/">
                                <img class="w-20" src="{{ asset('img/logo.png') }}" alt="traiteur_local">
                                <div class="logo-ext tracking-widest text-sm md:text-2xl font-semibold italic rounded text-white">Au pré des saveurs</div>
                            </a>
                        </div>

                        <div class="hidden md:flex md:flex-row justify-end content-center">
                            <a class="flex text-white no-underline hover:text-indigo-200 hover:text-underline text-center h-10 p-2 md:h-auto md:p-4"
                                href="/" data-te-nav-link-ref data-te-ripple-init data-te-ripple-color="light">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                    stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                    <path stroke-linecap="round" stroke-linejoin="round"
                                        d="M2.25 12l8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" />
                                </svg> &nbsp;
                                Accueil
                            </a>

                            <a class="flex text-white no-underline hover:text-indigo-200 hover:text-underline text-center h-10 p-2 md:h-auto md:p-4"
                                href="{{ route('about') }}" data-te-nav-link-ref data-te-ripple-init
                                data-te-ripple-color="light">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                    stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                    <path stroke-linecap="round" stroke-linejoin="round"
                                        d="M11.25 11.25l.041-.02a.75.75 0 011.063.852l-.708 2.836a.75.75 0 001.063.853l.041-.021M21 12a9 9 0 11-18 0 9 9 0 0118 0zm-9-3.75h.008v.008H12V8.25z" />
                                </svg> &nbsp;
                                A Propos
                            </a>

                            {{-- <a class="flex text-white no-underline hover:text-indigo-200 hover:text-underline text-center h-10 p-2 md:h-auto md:p-4"
                                    href="#contact" data-te-nav-link-ref data-te-ripple-init
                                    data-te-ripple-color="light">
                                    Rejoignez nous &nbsp;
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                        stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                        <path stroke-linecap="round" stroke-linejoin="round"
                                            d="M6 12L3.269 3.126A59.768 59.768 0 0121.485 12 59.77 59.77 0 013.27 20.876L5.999 12zm0 0h7.5" />
                                    </svg>
                                </a> --}}
                        </div>

                        <!-- Sidenav -->
                        <nav id="sidenav-7"
                            class="fixed right-0 z-[1035] h-screen w-60 translate-x-full overflow-hidden bg-white shadow-[0_4px_12px_0_rgba(0,0,0,0.07),_0_2px_4px_rgba(0,0,0,0.05)] data-[te-sidenav-hidden='false']:-translate-x-0 dark:bg-zinc-800"
                            style="top: 7rem" data-te-sidenav-init data-te-sidenav-hidden="true"
                            data-te-sidenav-right="true">
                            <ul class="relative m-0 list-none px-[0.2rem]" data-te-sidenav-menu-ref>
                                <li class="relative">
                                    <a class="flex h-12 cursor-pointer items-center truncate rounded-[5px] px-6 py-4 text-[0.875rem] text-gray-600 outline-none transition duration-300 ease-linear hover:bg-slate-50 hover:text-inherit hover:outline-none focus:bg-slate-50 focus:text-inherit focus:outline-none active:bg-slate-50 active:text-inherit active:outline-none data-[te-sidenav-state-active]:text-inherit data-[te-sidenav-state-focus]:outline-none motion-reduce:transition-none dark:text-gray-300 dark:hover:bg-white/10 dark:focus:bg-white/10 dark:active:bg-white/10"
                                        data-te-sidenav-link-ref>
                                        <span
                                            class="mr-4 [&>svg]:h-4 [&>svg]:w-4 [&>svg]:text-gray-400 dark:[&>svg]:text-gray-300">
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                                stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                                <path stroke-linecap="round" stroke-linejoin="round"
                                                    d="M2.25 12l8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" />
                                            </svg>
                                        </span>
                                        <span>Accueil</span>
                                    </a>
                                </li>
                                <li class="relative">
                                    <a class="flex h-12 cursor-pointer items-center truncate rounded-[5px] px-6 py-4 text-[0.875rem] text-gray-600 outline-none transition duration-300 ease-linear hover:bg-slate-50 hover:text-inherit hover:outline-none focus:bg-slate-50 focus:text-inherit focus:outline-none active:bg-slate-50 active:text-inherit active:outline-none data-[te-sidenav-state-active]:text-inherit data-[te-sidenav-state-focus]:outline-none motion-reduce:transition-none dark:text-gray-300 dark:hover:bg-white/10 dark:focus:bg-white/10 dark:active:bg-white/10"
                                        data-te-sidenav-link-ref>
                                        <span
                                            class="mr-4 [&>svg]:h-4 [&>svg]:w-4 [&>svg]:text-gray-400 dark:[&>svg]:text-gray-300">
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                                stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                                <path stroke-linecap="round" stroke-linejoin="round"
                                                    d="M11.25 11.25l.041-.02a.75.75 0 011.063.852l-.708 2.836a.75.75 0 001.063.853l.041-.021M21 12a9 9 0 11-18 0 9 9 0 0118 0zm-9-3.75h.008v.008H12V8.25z" />
                                            </svg>
                                        </span>
                                        <span>A Propos</span>
                                    </a>
                                </li>
                                {{-- <li class="relative">
                                        <a class="flex h-12 cursor-pointer items-center truncate rounded-[5px] px-6 py-4 text-[0.875rem] text-gray-600 outline-none transition duration-300 ease-linear hover:bg-slate-50 hover:text-inherit hover:outline-none focus:bg-slate-50 focus:text-inherit focus:outline-none active:bg-slate-50 active:text-inherit active:outline-none data-[te-sidenav-state-active]:text-inherit data-[te-sidenav-state-focus]:outline-none motion-reduce:transition-none dark:text-gray-300 dark:hover:bg-white/10 dark:focus:bg-white/10 dark:active:bg-white/10"
                                            data-te-sidenav-link-ref>
                                            <span
                                                class="mr-4 [&>svg]:h-4 [&>svg]:w-4 [&>svg]:text-gray-400 dark:[&>svg]:text-gray-300">
                                                <svg xmlns="http://www.w3.org/2000/svg" fill="none"
                                                    viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor"
                                                    class="w-6 h-6">
                                                    <path stroke-linecap="round" stroke-linejoin="round"
                                                        d="M6 12L3.269 3.126A59.768 59.768 0 0121.485 12 59.77 59.77 0 013.27 20.876L5.999 12zm0 0h7.5" />
                                                </svg>
                                            </span>
                                            <span>Rejoignez nous</span>
                                        </a>
                                    </li> --}}
                            </ul>
                        </nav>
                        <!-- Sidenav -->

                        <!-- Toggler -->
                        <button
                            class="border-0 bg-transparent px-2 text-xl leading-none transition-shadow duration-150 ease-in-out hover:text-white focus:text-white dark:hover:text-white dark:focus:text-white md:hidden"
                            data-te-sidenav-toggle-ref data-te-target="#sidenav-7" aria-controls="#sidenav-7"
                            aria-haspopup="true">
                            <span class="block [&>svg]:h-5 [&>svg]:w-6 [&>svg]:text-white">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="#fff"
                                    class="h-6 w-6">
                                    <path fill-rule="evenodd"
                                        d="M3 6.75A.75.75 0 013.75 6h16.5a.75.75 0 010 1.5H3.75A.75.75 0 013 6.75zM3 12a.75.75 0 01.75-.75h16.5a.75.75 0 010 1.5H3.75A.75.75 0 013 12zm0 5.25a.75.75 0 01.75-.75h16.5a.75.75 0 010 1.5H3.75a.75.75 0 01-.75-.75z"
                                        clip-rule="evenodd" />
                                </svg>
                            </span>
                        </button>
                        <!-- Toggler -->
                    </div>

                </div>
            </div>
        </div>
    </nav>

    <div class="h-screen w-full bg-fixed bg-center bg-cover" style="background-image:url('img/parallax.jpg');">
        <div class="px-8 md:px-14 mx-auto flex flex-wrap flex-col md:flex-row items-center h-full py-2"
            style="background-color: rgba(187, 175, 123, .6)">
            <!--Left Col-->
            <div class="pt-24 flex flex-col md:w-1/2 justify-center items-center md:items-start">
                <h1
                    class="my-4 text-3xl md:text-4xl text-white font-bold leading-tight text-center md:text-left slide-in-bottom-h1">
                    Trouver des traiteurs proches de chez vous</h1>
                <p class="leading-normal text-base md:text-xl mb-8 text-center md:text-left slide-in-bottom-subtitle">
                    Explorer de nouvelles saveurs et cuisines sans quitter votre domicile en commandant en ligne
                    avec Traiteur Local
                </p>

                <div class="border rounded-lg text-center my-2 px-8 py-4 bg-white w-full fade-in">
                    <h2 class="font-bold ">Traiteur Local, Au pré des saveurs</h2>
                </div>

                <p class="text-white font-bold pb-8 lg:pb-6 text-center md:text-left fade-in">Télécharger
                    l'application </p>
                <div class="flex w-full justify-center md:justify-start pb-24 lg:pb-0 fade-in">
                    <img src="{{ asset('img/App Store.svg') }}" class="h-12 pr-4 bounce-top-icons">
                    <img src="{{ asset('img/Play Store.svg') }}" class="h-12 bounce-top-icons">
                </div>

            </div>

            <!--Right Col-->
            <div class="hidden md:block md:w-1/2 overflow-y-hidden py-6">
                {{-- <img class="w-5/6 mx-auto lg:mr-0 slide-in-bottom" src="{{ asset('img/banner.png') }}"> --}}
                <div id="carouselDarkVariant" class="relative" data-te-carousel-init data-te-ride="carousel">

                    <!-- Carousel items -->
                    <div class="relative w-full overflow-hidden after:clear-both after:block after:content-['']">
                        <!-- First item -->
                        <div class="relative float-left -mr-[100%] w-full !transform-none opacity-0 transition-opacity duration-[600ms] ease-in-out motion-reduce:transition-none"
                            data-te-carousel-fade data-te-carousel-item data-te-carousel-active>
                            <img src="{{ asset('img/slide-entree.png') }}" class="test block w-1/2 mx-auto"
                                alt="slide-entree" />
                        </div>
                        <!-- Second item -->
                        <div class="relative float-left -mr-[100%] hidden w-full !transform-none opacity-0 transition-opacity duration-[600ms] ease-in-out motion-reduce:transition-none"
                            data-te-carousel-fade data-te-carousel-item>
                            <img src="{{ asset('img/slide-plat.png') }}" class="test block w-1/2 mx-auto"
                                alt="slide-plat" />
                        </div>
                        <!-- Third item -->
                        <div class="relative float-left -mr-[100%] hidden w-full !transform-none opacity-0 transition-opacity duration-[600ms] ease-in-out motion-reduce:transition-none"
                            data-te-carousel-fade data-te-carousel-item>
                            <img src="{{ asset('img/slide-dessert.png') }}" class="test block w-1/2 mx-auto"
                                alt="slide-dessert" />
                        </div>
                        <!-- Third item -->
                        <div class="relative float-left -mr-[100%] hidden w-full !transform-none opacity-0 transition-opacity duration-[600ms] ease-in-out motion-reduce:transition-none"
                            data-te-carousel-fade data-te-carousel-item>
                            <img src="{{ asset('img/slide-boisson.jpg') }}"
                                class="test block w-1/2 mx-auto rounded-full" alt="slide-boisson" />
                        </div>
                    </div>

                    <!-- Carousel controls - prev item-->
                    <button
                        class="absolute bottom-0 left-0 top-0 z-[1] flex w-[15%] items-center justify-center border-0 bg-none p-0 text-center text-black opacity-50 transition-opacity duration-150 ease-[cubic-bezier(0.25,0.1,0.25,1.0)] hover:text-black hover:no-underline hover:opacity-90 hover:outline-none focus:text-black focus:no-underline focus:opacity-90 focus:outline-none motion-reduce:transition-none"
                        type="button" data-te-target="#carouselDarkVariant" data-te-slide="prev">
                        <span class="inline-block h-8 w-8 dark:grayscale">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                stroke-width="1.5" stroke="currentColor" class="h-6 w-6">
                                <path stroke-linecap="round" stroke-linejoin="round"
                                    d="M15.75 19.5L8.25 12l7.5-7.5" />
                            </svg>
                        </span>
                        <span
                            class="!absolute !-m-px !h-px !w-px !overflow-hidden !whitespace-nowrap !border-0 !p-0 ![clip:rect(0,0,0,0)]">Previous</span>
                    </button>
                    <!-- Carousel controls - next item-->
                    <button
                        class="absolute bottom-0 right-0 top-0 z-[1] flex w-[15%] items-center justify-center border-0 bg-none p-0 text-center text-black opacity-50 transition-opacity duration-150 ease-[cubic-bezier(0.25,0.1,0.25,1.0)] hover:text-black hover:no-underline hover:opacity-90 hover:outline-none focus:text-black focus:no-underline focus:opacity-90 focus:outline-none motion-reduce:transition-none"
                        type="button" data-te-target="#carouselDarkVariant" data-te-slide="next">
                        <span class="inline-block h-8 w-8 dark:grayscale">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                stroke-width="1.5" stroke="currentColor" class="h-6 w-6">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" />
                            </svg>
                        </span>
                        <span
                            class="!absolute !-m-px !h-px !w-px !overflow-hidden !whitespace-nowrap !border-0 !p-0 ![clip:rect(0,0,0,0)]">Next</span>
                    </button>
                </div>
            </div>
        </div>
    </div>

    <div class="">
        <section class="text-gray-600 body-font">
            <div class="container px-5 py-24 mx-auto">
                <h2 class="font-bold text-center text-2xl my-2">Ce que nous proposons</h2>
                <!--Tabs navigation-->
                <ul class="mb-5 flex list-none flex-row flex-wrap border-b-0 pl-0" role="tablist" data-te-nav-ref>
                    <li role="presentation" class="flex-grow basis-0 text-center">
                        <a href="#tabs-all"
                            class="my-2 block border-x-0 border-b-2 border-t-0 border-transparent px-7 pb-3.5 pt-4 text-xs font-medium uppercase leading-tight text-neutral-500 hover:isolate hover:border-transparent hover:bg-neutral-100 focus:isolate focus:border-transparent data-[te-nav-active]:border-primary data-[te-nav-active]:text-primary dark:text-neutral-400 dark:hover:bg-transparent dark:data-[te-nav-active]:border-primary-400 dark:data-[te-nav-active]:text-primary-400"
                            data-te-toggle="pill" data-te-target="#tabs-all" data-te-nav-active role="tab"
                            aria-controls="tabs-all" aria-selected="true">Tout</a>
                    </li>
                    <li role="presentation" class="flex-grow basis-0 text-center">
                        <a href="#tabs-entry"
                            class="my-2 block border-x-0 border-b-2 border-t-0 border-transparent px-7 pb-3.5 pt-4 text-xs font-medium uppercase leading-tight text-neutral-500 hover:isolate hover:border-transparent hover:bg-neutral-100 focus:isolate focus:border-transparent data-[te-nav-active]:border-primary data-[te-nav-active]:text-primary dark:text-neutral-400 dark:hover:bg-transparent dark:data-[te-nav-active]:border-primary-400 dark:data-[te-nav-active]:text-primary-400"
                            data-te-toggle="pill" data-te-target="#tabs-entry" role="tab"
                            aria-controls="tabs-entry" aria-selected="false">Entrées</a>
                    </li>
                    <li role="presentation" class="flex-grow basis-0 text-center">
                        <a href="#tabs-plat"
                            class="my-2 block border-x-0 border-b-2 border-t-0 border-transparent px-7 pb-3.5 pt-4 text-xs font-medium uppercase leading-tight text-neutral-500 hover:isolate hover:border-transparent hover:bg-neutral-100 focus:isolate focus:border-transparent data-[te-nav-active]:border-primary data-[te-nav-active]:text-primary dark:text-neutral-400 dark:hover:bg-transparent dark:data-[te-nav-active]:border-primary-400 dark:data-[te-nav-active]:text-primary-400"
                            data-te-toggle="pill" data-te-target="#tabs-plat" role="tab"
                            aria-controls="tabs-plat" aria-selected="false">Plats</a>
                    </li>
                    <li role="presentation" class="flex-grow basis-0 text-center">
                        <a href="#tabs-dessert"
                            class="my-2 block border-x-0 border-b-2 border-t-0 border-transparent px-7 pb-3.5 pt-4 text-xs font-medium uppercase leading-tight text-neutral-500 hover:isolate hover:border-transparent hover:bg-neutral-100 focus:isolate focus:border-transparent data-[te-nav-active]:border-primary data-[te-nav-active]:text-primary dark:text-neutral-400 dark:hover:bg-transparent dark:data-[te-nav-active]:border-primary-400 dark:data-[te-nav-active]:text-primary-400"
                            data-te-toggle="pill" data-te-target="#tabs-dessert" role="tab"
                            aria-controls="tabs-dessert" aria-selected="false">Desserts</a>
                    </li>
                    <li role="presentation" class="flex-grow basis-0 text-center">
                        <a href="#tabs-drink"
                            class="my-2 block border-x-0 border-b-2 border-t-0 border-transparent px-7 pb-3.5 pt-4 text-xs font-medium uppercase leading-tight text-neutral-500 hover:isolate hover:border-transparent hover:bg-neutral-100 focus:isolate focus:border-transparent data-[te-nav-active]:border-primary data-[te-nav-active]:text-primary dark:text-neutral-400 dark:hover:bg-transparent dark:data-[te-nav-active]:border-primary-400 dark:data-[te-nav-active]:text-primary-400"
                            data-te-toggle="pill" data-te-target="#tabs-drink" role="tab"
                            aria-controls="tabs-drink" aria-selected="false">Boissons</a>
                    </li>
                </ul>

                <!--Tabs content-->
                <div class="mb-6">
                    <div class="hidden opacity-100 transition-opacity duration-150 ease-linear data-[te-tab-active]:block"
                        id="tabs-all" role="tabpanel" aria-labelledby="tabs-home-tab02" data-te-tab-active>
                        <div class="container mx-auto px-5 py-2 lg:px-32 lg:pt-12">
                            <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
                                <div class="border p-4 rounded-md">
                                    <div class="w-full p-1 md:p-2">
                                        <img alt="gallery"
                                            class="block h-full w-full rounded-lg object-cover object-center"
                                            src="{{ asset('img/slide-entree.png') }}" />
                                    </div>
                                </div>
                                <div class="border p-4 rounded-md">
                                    <div class="w-full p-1 md:p-2">
                                        <img alt="gallery"
                                            class="block h-full w-full rounded-lg object-cover object-center"
                                            src="{{ asset('img/slide-plat.png') }}" />
                                    </div>
                                </div>
                                <div class="border p-4 rounded-md">
                                    <div class="w-full p-1 md:p-2">
                                        <img alt="gallery"
                                            class="block h-full w-full rounded-lg object-cover object-center"
                                            src="{{ asset('img/slide-dessert.png') }}" />
                                    </div>
                                </div>
                                <div class="border p-4 rounded-md">
                                    <div class="w-full p-1 md:p-2">
                                        <img alt="gallery"
                                            class="block h-full w-full rounded-lg object-cover object-center"
                                            src="{{ asset('img/slide-boisson.jpg') }}" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="hidden opacity-0 transition-opacity duration-150 ease-linear data-[te-tab-active]:block"
                        id="tabs-entry" role="tabpanel" aria-labelledby="tabs-profile-tab02">
                        <div class="container mx-auto px-5 py-2 lg:px-32 lg:pt-12">
                            <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
                                <div class="border p-4 rounded-md">
                                    <div class="w-full p-1 md:p-2">
                                        <img alt="gallery"
                                            class="block h-full w-full rounded-lg object-cover object-center"
                                            src="{{ asset('img/slide-plat.png') }}" />
                                    </div>
                                </div>
                                <div class="border p-4 rounded-md">
                                    <div class="w-full p-1 md:p-2">
                                        <img alt="gallery"
                                            class="block h-full w-full rounded-lg object-cover object-center"
                                            src="{{ asset('img/slide-plat.png') }}" />
                                    </div>
                                </div>
                                <div class="border p-4 rounded-md">
                                    <div class="w-full p-1 md:p-2">
                                        <img alt="gallery"
                                            class="block h-full w-full rounded-lg object-cover object-center"
                                            src="{{ asset('img/slide-plat.png') }}" />
                                    </div>
                                </div>
                                <div class="border p-4 rounded-md">
                                    <div class="w-full p-1 md:p-2">
                                        <img alt="gallery"
                                            class="block h-full w-full rounded-lg object-cover object-center"
                                            src="{{ asset('img/slide-plat.png') }}" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="hidden opacity-0 transition-opacity duration-150 ease-linear data-[te-tab-active]:block"
                        id="tabs-plat" role="tabpanel" aria-labelledby="tabs-profile-tab02">
                        <div class="container mx-auto px-5 py-2 lg:px-32 lg:pt-12">
                            <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
                                <div class="border p-4 rounded-md">
                                    <div class="w-full p-1 md:p-2">
                                        <img alt="gallery"
                                            class="block h-full w-full rounded-lg object-cover object-center"
                                            src="{{ asset('img/slide-plat.png') }}" />
                                    </div>
                                </div>
                                <div class="border p-4 rounded-md">
                                    <div class="w-full p-1 md:p-2">
                                        <img alt="gallery"
                                            class="block h-full w-full rounded-lg object-cover object-center"
                                            src="{{ asset('img/slide-plat.png') }}" />
                                    </div>
                                </div>
                                <div class="border p-4 rounded-md">
                                    <div class="w-full p-1 md:p-2">
                                        <img alt="gallery"
                                            class="block h-full w-full rounded-lg object-cover object-center"
                                            src="{{ asset('img/slide-plat.png') }}" />
                                    </div>
                                </div>
                                <div class="border p-4 rounded-md">
                                    <div class="w-full p-1 md:p-2">
                                        <img alt="gallery"
                                            class="block h-full w-full rounded-lg object-cover object-center"
                                            src="{{ asset('img/slide-plat.png') }}" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="hidden opacity-0 transition-opacity duration-150 ease-linear data-[te-tab-active]:block"
                        id="tabs-dessert" role="tabpanel" aria-labelledby="tabs-contact-tab02">
                        <div class="container mx-auto px-5 py-2 lg:px-32 lg:pt-12">
                            <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
                                <div class="border p-4 rounded-md">
                                    <div class="w-full p-1 md:p-2">
                                        <img alt="gallery"
                                            class="block h-full w-full rounded-lg object-cover object-center"
                                            src="{{ asset('img/slide-plat.png') }}" />
                                    </div>
                                </div>
                                <div class="border p-4 rounded-md">
                                    <div class="w-full p-1 md:p-2">
                                        <img alt="gallery"
                                            class="block h-full w-full rounded-lg object-cover object-center"
                                            src="{{ asset('img/slide-plat.png') }}" />
                                    </div>
                                </div>
                                <div class="border p-4 rounded-md">
                                    <div class="w-full p-1 md:p-2">
                                        <img alt="gallery"
                                            class="block h-full w-full rounded-lg object-cover object-center"
                                            src="{{ asset('img/slide-plat.png') }}" />
                                    </div>
                                </div>
                                <div class="border p-4 rounded-md">
                                    <div class="w-full p-1 md:p-2">
                                        <img alt="gallery"
                                            class="block h-full w-full rounded-lg object-cover object-center"
                                            src="{{ asset('img/slide-plat.png') }}" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="hidden opacity-0 transition-opacity duration-150 ease-linear data-[te-tab-active]:block"
                        id="tabs-drink" role="tabpanel" aria-labelledby="tabs-contact-tab02">
                        <div class="container mx-auto px-5 py-2 lg:px-32 lg:pt-12">
                            <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
                                <div class="border p-4 rounded-md">
                                    <div class="w-full p-1 md:p-2">
                                        <img alt="gallery"
                                            class="block h-full w-full rounded-lg object-cover object-center"
                                            src="{{ asset('img/slide-plat.png') }}" />
                                    </div>
                                </div>
                                <div class="border p-4 rounded-md">
                                    <div class="w-full p-1 md:p-2">
                                        <img alt="gallery"
                                            class="block h-full w-full rounded-lg object-cover object-center"
                                            src="{{ asset('img/slide-plat.png') }}" />
                                    </div>
                                </div>
                                <div class="border p-4 rounded-md">
                                    <div class="w-full p-1 md:p-2">
                                        <img alt="gallery"
                                            class="block h-full w-full rounded-lg object-cover object-center"
                                            src="{{ asset('img/slide-plat.png') }}" />
                                    </div>
                                </div>
                                <div class="border p-4 rounded-md">
                                    <div class="w-full p-1 md:p-2">
                                        <img alt="gallery"
                                            class="block h-full w-full rounded-lg object-cover object-center"
                                            src="{{ asset('img/slide-plat.png') }}" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <div class="py-12" style="background-color: #bdd5f8">
        <div class="">
            <!--Main-->
            <div class="container px-6 mx-auto flex flex-wrap flex-col md:flex-row items-center">

                <section class="text-gray-600 body-font">
                    <div class="container px-5 py-12 mx-auto">
                        <div class="flex flex-wrap -m-4">
                            <div class="p-4 md:w-1/2">
                                <div class="h-full rounded-lg overflow-hidden">
                                    <img class="h:full w-full object-cover object-center"
                                        src="{{ asset('img/chief.jpg') }}" alt="blog">
                                </div>
                            </div>
                            <div class="p-4 md:w-1/2">
                                <div
                                    class="h-full border-2 border-gray-100 border-opacity-60 rounded-lg overflow-hidden">
                                    <div class="p-6">
                                        <h2 class="tracking-widest text-xs title-font font-medium text-white mb-1">
                                            Traiteur
                                        </h2>
                                        <h1 class="title-font text-lg font-medium text-white mb-3">Par vous</h1>
                                        <p class="leading-relaxed mb-3 text-white">
                                            Offrez de nouvelles saveurs à travers notre application. Partager votre
                                            passion
                                            et savoir faire venant de votre expérience culinaire professionnelle à la
                                            table
                                            de vos clients. Organiser la planification de vos évènements grâce notre
                                            plateforme.
                                        </p>
                                        <div class="flex items-center flex-wrap">
                                            <a href="{{ route('login.traitor') }}"
                                                class="text-indigo-500 inline-flex items-center md:mb-2 lg:mb-0">Se connecter
                                                <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor"
                                                    stroke-width="2" fill="none" stroke-linecap="round"
                                                    stroke-linejoin="round">
                                                    <path d="M5 12h14"></path>
                                                    <path d="M12 5l7 7-7 7"></path>
                                                </svg>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>

    <div class="">
        <div class="">
            <!--Main-->
            <div class="container px-6 mx-auto flex flex-wrap flex-col md:flex-row items-center">
                <section class="body-font">
                    <div class="container px-5 py-24 mx-auto">
                        <div class="flex flex-wrap -m-4">
                            <div class="p-4 md:w-1/2">
                                <div
                                    class="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden">
                                    <div class="p-6">
                                        <h2 class="tracking-widest text-xs title-font font-medium text-gray-400 mb-1">
                                            Client
                                        </h2>
                                        <h1 class="title-font text-lg font-medium text-gray-900 mb-3">Pour vous</h1>
                                        <p class="leading-relaxed mb-3">
                                            Venez découvrir notre carte d'entrées, plats desserts, et/ou boissons et
                                            faites vous livrer par le traiteur.
                                        </p>
                                        <div class="flex items-center flex-wrap ">
                                            <a href="#"
                                                class="text-indigo-500 inline-flex items-center md:mb-2 lg:mb-0">Télécharger
                                                l'application
                                                <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor"
                                                    stroke-width="2" fill="none" stroke-linecap="round"
                                                    stroke-linejoin="round">
                                                    <path d="M5 12h14"></path>
                                                    <path d="M12 5l7 7-7 7"></path>
                                                </svg>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="p-4 md:w-1/2">
                                <div class="h-full rounded-lg overflow-hidden">
                                    <img class="h:full w-full object-cover object-center"
                                        src="{{ asset('img/food.jpg') }}" alt="blog">
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>

    <div id="testimonies"
        class="p-4 flex items-center justify-center h-sceen md:h-96 bg-fixed bg-center bg-cover brightness-100"
        style="background-image:url('img/parallax.jpg')">
        <!--Carousel-->
        <div class="absolute w-full h-sceen md:h-96" style="background: rgba(17, 22, 24, .5)"></div>
        <div id="carouselExampleCaptions" class="relative" data-te-carousel-init data-te-carousel-slide
            data-te-ride="carousel">
            <div class="relative w-full overflow-hidden after:clear-both after:block after:content-['']">
                <!--First Testimonial / Carousel item-->
                <div class="relative float-left -mr-[100%] hidden w-full text-center transition-transform duration-[600ms] ease-in-out motion-reduce:transition-none"
                    data-te-carousel-active data-te-carousel-item style="backface-visibility: hidden">
                    <p class="mx-auto w-2/3 text-xl italic text-white">
                        "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit,
                        error amet numquam iure provident voluptate esse quasi, voluptas
                        nostrum quisquam!"
                    </p>
                    <div class="mb-6 mt-12 flex justify-center">
                        <img src="https://tecdn.b-cdn.net/img/Photos/Avatars/img%20(2).webp"
                            class="h-24 w-24 rounded-full shadow-lg dark:shadow-black/30" alt="smaple image" />
                    </div>
                    <p class="text-white">- Anna Morian</p>
                </div>

                <!--Second Testimonial / Carousel item-->
                <div class="relative float-left -mr-[100%] hidden w-full text-center transition-transform duration-[600ms] ease-in-out motion-reduce:transition-none"
                    data-te-carousel-item style="backface-visibility: hidden">
                    <p class="mx-auto w-2/3 text-xl italic text-white">
                        "Neque cupiditate assumenda in maiores repudiandae mollitia
                        adipisci maiores repudiandae mollitia consectetur adipisicing
                        architecto elit sed adipiscing elit."
                    </p>
                    <div class="mb-6 mt-12 flex justify-center">
                        <img src="https://tecdn.b-cdn.net/img/Photos/Avatars/img%20(31).webp"
                            class="h-24 w-24 rounded-full shadow-lg dark:shadow-black/30" alt="smaple image" />
                    </div>
                    <p class="text-white">- Teresa May</p>
                </div>

                <!--Third Testimonial / Carousel item-->
                <div class="relative float-left -mr-[100%] hidden w-full text-center transition-transform duration-[600ms] ease-in-out motion-reduce:transition-none"
                    data-te-carousel-item style="backface-visibility: hidden">
                    <p class="mx-auto w-2/3 text-xl italic text-white">
                        "Duis aute irure dolor in reprehenderit in voluptate velit esse
                        cillum dolore eu fugiat nulla pariatur est laborum neque
                        cupiditate assumenda in maiores."
                    </p>
                    <div class="mb-6 mt-12 flex justify-center">
                        <img src="https://tecdn.b-cdn.net/img/Photos/Avatars/img%20(10).webp"
                            class="h-24 w-24 rounded-full shadow-lg dark:shadow-black/30" alt="smaple image" />
                    </div>
                    <p class="text-white">- Kate Allise</p>
                </div>
            </div>

            <!--Carousel Controls - prev item-->
            <button
                class="absolute bottom-0 left-0 top-0 z-[1] flex w-[15%] items-center justify-center border-0 bg-none p-0 text-center text-white opacity-50 transition-opacity duration-150 ease-[cubic-bezier(0.25,0.1,0.25,1.0)] hover:text-white hover:no-underline hover:opacity-90 hover:outline-none focus:text-white focus:no-underline focus:opacity-90 focus:outline-none motion-reduce:transition-none dark:text-white dark:opacity-50 dark:hover:text-white dark:focus:text-white"
                type="button" data-te-target="#carouselExampleCaptions" data-te-slide="prev">
                <span class="inline-block h-8 w-8">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                        stroke="currentColor" class="h-6 w-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 19.5L8.25 12l7.5-7.5" />
                    </svg>
                </span>
                <span
                    class="!absolute !-m-px !h-px !w-px !overflow-hidden !whitespace-nowrap !border-0 !p-0 ![clip:rect(0,0,0,0)]">Previous</span>
            </button>
            <!--Carousel Controls - next item-->
            <button
                class="absolute bottom-0 right-0 top-0 z-[1] flex w-[15%] items-center justify-center border-0 bg-none p-0 text-center text-white opacity-50 transition-opacity duration-150 ease-[cubic-bezier(0.25,0.1,0.25,1.0)] hover:text-white hover:no-underline hover:opacity-90 hover:outline-none focus:text-white focus:no-underline focus:opacity-90 focus:outline-none motion-reduce:transition-none dark:text-white dark:opacity-50 dark:hover:text-white dark:focus:text-white"
                type="button" data-te-target="#carouselExampleCaptions" data-te-slide="next">
                <span class="inline-block h-8 w-8">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                        stroke="currentColor" class="h-6 w-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" />
                    </svg>
                </span>
                <span
                    class="!absolute !-m-px !h-px !w-px !overflow-hidden !whitespace-nowrap !border-0 !p-0 ![clip:rect(0,0,0,0)]">Next</span>
            </button>
        </div>
    </div>

    <div id="contact">
        <section class="text-gray-600 body-font">
            <div class="container px-5 py-12 mx-auto">
                <div class="flex flex-wrap items-center justify-center -m-4">
                    <div class="p-4">

                        @if (Session::has('success'))
                            <div class="mb-4 rounded-lg bg-success-100 px-6 py-5 text-base text-success-700"
                                role="alert">
                                {{ Session::get('success') }}
                            </div>
                        @endif

                        <div class="block rounded-lg bg-white p-6 shadow-xl dark:bg-neutral-700">
                            <h2 class="text-center font-bold mb-2">Contact</h2>
                            <form action="{{ route('contact.store') }}" id="form" method="POST"
                                x-data="validateContactForm()" x-init="$watch('name', value => { validate('name') })
                                $watch('email', value => { validate('email') })
                                $watch('message', value => { validate('message') })">
                                @csrf

                                <!--Name input-->
                                <div class="relative mb-6">
                                    <label for="name" class="">Nom
                                    </label>
                                    <input x-model="name" type="text" id="name" name="name"
                                        class="peer block min-h-[auto] w-full rounded border bg-transparent px-3 py-[0.32rem] leading-[1.6] outline-none transition-all duration-200 ease-linear focus:placeholder:opacity-100 data-[te-input-state-active]:placeholder:opacity-100 motion-reduce:transition-none dark:text-neutral-200 dark:placeholder:text-neutral-200 [&:not([data-te-input-placeholder-active])]:placeholder:opacity-0" />
                                    <x-input-error :messages="$errors->get('name')" class="mt-2" />
                                    <span class="text-sm italic text-red-500 mt-2">
                                        <div x-text="validation.name.message"></div>
                                    </span>
                                </div>

                                <!--Email input-->
                                <div class="relative mb-6">
                                    <label for="email" class="">Email
                                    </label>
                                    <input x-model="email" type="email" name="email"
                                        class="peer block min-h-[auto] w-full rounded border bg-transparent px-3 py-[0.32rem] leading-[1.6] outline-none transition-all duration-200 ease-linear focus:placeholder:opacity-100 data-[te-input-state-active]:placeholder:opacity-100 motion-reduce:transition-none dark:text-neutral-200 dark:placeholder:text-neutral-200 [&:not([data-te-input-placeholder-active])]:placeholder:opacity-0"
                                        id="email" placeholder="Email" />
                                    <x-input-error :messages="$errors->get('email')" class="mt-2" />
                                    <span class="text-sm italic text-red-500 mt-2">
                                        <div x-text="validation.email.message"></div>
                                    </span>
                                </div>

                                <!--object input-->
                                <div class="relative mb-6">
                                    <label for="object" class="">Objet
                                    </label>
                                    <input x-model="object" type="text" name="object"
                                        class="peer block min-h-[auto] w-full rounded border bg-transparent px-3 py-[0.32rem] leading-[1.6] outline-none transition-all duration-200 ease-linear focus:placeholder:opacity-100 data-[te-input-state-active]:placeholder:opacity-100 motion-reduce:transition-none dark:text-neutral-200 dark:placeholder:text-neutral-200 [&:not([data-te-input-placeholder-active])]:placeholder:opacity-0"
                                        id="object" placeholder="Email" />
                                    <x-input-error :messages="$errors->get('object')" class="mt-2" />
                                    <span class="text-sm italic text-red-500 mt-2">
                                        <div x-text="validation.object.message"></div>
                                    </span>
                                </div>

                                <!--Message textarea-->
                                <div class="relative mb-6">
                                    <label for="message" class="">Message
                                    </label>
                                    <textarea x-model="message" name="message"
                                        class="peer block min-h-[auto] w-full rounded border bg-transparent px-3 py-[0.32rem] leading-[1.6] outline-none transition-all duration-200 ease-linear focus:placeholder:opacity-100 data-[te-input-state-active]:placeholder:opacity-100 motion-reduce:transition-none dark:text-neutral-200 dark:placeholder:text-neutral-200 [&:not([data-te-input-placeholder-active])]:placeholder:opacity-0"
                                        id="message" rows="3" placeholder="Message"></textarea>
                                    <x-input-error :messages="$errors->get('message')" class="mt-2" />
                                    <span class="text-sm italic text-red-500 mt-2">
                                        <div x-text="validation.message.message"></div>
                                    </span>
                                </div>

                                <!--Checkbox-->
                                {{-- <div class="mb-6 flex min-h-[1.5rem] items-center justify-center pl-[1.5rem]">
                                    <input
                                        class="relative float-left -ml-[1.5rem] mr-[6px] h-[1.125rem] w-[1.125rem] appearance-none rounded-[0.25rem] border-[0.125rem] border-solid border-neutral-300 outline-none before:pointer-events-none before:absolute before:h-[0.875rem] before:w-[0.875rem] before:scale-0 before:rounded-full before:bg-transparent before:opacity-0 before:shadow-[0px_0px_0px_13px_transparent] before:content-[''] checked:border-primary checked:bg-primary checked:before:opacity-[0.16] checked:after:absolute checked:after:-mt-px checked:after:ml-[0.25rem] checked:after:block checked:after:h-[0.8125rem] checked:after:w-[0.375rem] checked:after:rotate-45 checked:after:border-[0.125rem] checked:after:border-l-0 checked:after:border-t-0 checked:after:border-solid checked:after:border-white checked:after:bg-transparent checked:after:content-[''] hover:cursor-pointer hover:before:opacity-[0.04] hover:before:shadow-[0px_0px_0px_13px_rgba(0,0,0,0.6)] focus:shadow-none focus:transition-[border-color_0.2s] focus:before:scale-100 focus:before:opacity-[0.12] focus:before:shadow-[0px_0px_0px_13px_rgba(0,0,0,0.6)] focus:before:transition-[box-shadow_0.2s,transform_0.2s] focus:after:absolute focus:after:z-[1] focus:after:block focus:after:h-[0.875rem] focus:after:w-[0.875rem] focus:after:rounded-[0.125rem] focus:after:content-[''] checked:focus:before:scale-100 checked:focus:before:shadow-[0px_0px_0px_13px_#3b71ca] checked:focus:before:transition-[box-shadow_0.2s,transform_0.2s] checked:focus:after:-mt-px checked:focus:after:ml-[0.25rem] checked:focus:after:h-[0.8125rem] checked:focus:after:w-[0.375rem] checked:focus:after:rotate-45 checked:focus:after:rounded-none checked:focus:after:border-[0.125rem] checked:focus:after:border-l-0 checked:focus:after:border-t-0 checked:focus:after:border-solid checked:focus:after:border-white checked:focus:after:bg-transparent dark:border-neutral-600 dark:checked:border-primary dark:checked:bg-primary dark:focus:before:shadow-[0px_0px_0px_13px_rgba(255,255,255,0.4)] dark:checked:focus:before:shadow-[0px_0px_0px_13px_#3b71ca]"
                                        type="checkbox" value="" id="exampleCheck10" />
                                    <label class="inline-block pl-[0.15rem] hover:cursor-pointer"
                                        for="exampleCheck10">
                                        Envoyer moi une copie de ce message
                                    </label>
                                </div> --}}

                                <!-- Google Recaptcha -->
                                <div class="g-recaptcha my-4" data-sitekey={{ config('services.recaptcha.key') }}>
                                </div>

                                <!--Submit button-->
                                <button type="submit"
                                    class="dark:active:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.2),0_4px_18px_0_rgba(59,113,202,0.1)]] inline-block w-full rounded bg-primary px-6 pb-2 pt-2.5 text-xs font-medium uppercase leading-normal text-white shadow-[0_4px_9px_-4px_#3b71ca] transition duration-150 ease-in-out hover:bg-primary-600 hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:bg-primary-600 focus:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:outline-none focus:ring-0 active:bg-primary-700 active:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] dark:shadow-[0_4px_9px_-4px_rgba(59,113,202,0.5)] dark:hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.2),0_4px_18px_0_rgba(59,113,202,0.1)] dark:focus:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.2),0_4px_18px_0_rgba(59,113,202,0.1)]"
                                    data-te-ripple-init data-te-ripple-color="light"
                                    style="background-color: #4bad41">
                                    Envoyer
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <footer class="px-6 mx-auto flex flex-wrap flex-col md:flex-row items-center" style="background-color: #bbaf7b">
        <!--Footer-->

        <div class="w-full pt-16 pb-6 text-md text-center fade-in flex flex-col md:flex-row justify-between">
            <div class="my-2">
                <a class="text-white no-underline hover:no-underline" href="#">Mentions Légales</a> <span
                    class="text-white"> | </span>
                <a class="text-white no-underline hover:no-underline" href="#">Conditions Générales
                    d'utilisation</a> <span class="text-white"> | </span>
                <a class="text-white no-underline hover:no-underline" href="#">Conditions Générales de vente</a>
            </div>

            <div class="my-2">
                <a class="text-white no-underline hover:no-underline" href="#">&copy; Traiteur Local
                    2023</a>
                @if (Route::has('login.admin'))
                    <a class="text-white no-underline hover:no-underline" href="{{ route('login.admin') }}">&copy;
                        Administration</a>
                @endif
            </div>
        </div>
    </footer>

    <script async src="//www.google.com/recaptcha/api.js"></script>
    <script>
        function onSubmit(token) {
            document.getElementById("form").submit();
        }
    </script>

    <script src="https://cdn.jsdelivr.net/npm/tw-elements/dist/js/tw-elements.umd.min.js"></script>

</body>

</html>
